server:
  port: 8082
spring:
  application:
    name: cart-service
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: manoj
    password: mano123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true